#include <bits/stdc++.h>
using namespace std;

/*

##  Problem Statement

Given a positive integer `n`, simulate the following algorithm:

* If `n` is even, divide it by 2.
* If `n` is odd, multiply it by 3 and add 1.
* Repeat the process until `n` becomes 1.

### Input

A single integer `n` (`1 ≤ n ≤ 10^6`).

### Output

Print all the values of `n` generated by the algorithm, separated by spaces. The sequence should end with `1`.

*/
 
void weird_algo(long long n) {
    while (n != 1) {
        cout << n << " ";
        if (n & 1) n = 3 * n + 1;
        else n /= 2;
    }
    cout << 1 << "\n";
}
 
int main() {
    long long n;
    cin >> n;
    weird_algo(n);
    return 0;
